#!/bin/sh

system_type=$(uname -s)

echo "Installing oh-my-zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

echo "Installing Pyenv"
curl https://pyenv.run | bash

echo "Installing Zsh"
sudo apt install zsh
sudo chsh -s $(which zsh)

git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting

git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting

git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git $ZSH_CUSTOM/plugins/zsh-autocomplete
# if [ "$system_type" = "Darwin" ]; then
#
#   # possibly add something here to ensure iTerm2 is installed using Homebrew
#   # cask like in the previous example
#
#   if [ -d "$HOME/.iterm2" ]; then
#     echo "Setting iTerm preference folder"
#     defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
#   fi
#
# fi
